# Generated by Django 5.0.1 on 2024-02-21 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arl',
            fields=[
                ('idArl', models.AutoField(primary_key=True, serialize=False)),
                ('arl', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCargo', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=30)),
                ('contraseña', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('idCorte', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadCorte', models.FloatField(default=0.0)),
                ('medida', models.CharField(choices=[('m', 'metros'), ('k', 'kilos')], default='m', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('idEps', models.AutoField(primary_key=True, serialize=False)),
                ('eps', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('idMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=30)),
                ('cantidadMaterial', models.FloatField(default=0.0)),
                ('medida', models.CharField(choices=[('m', 'metros'), ('k', 'kilos'), ('u', 'unidaddes')], default='m', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=30)),
                ('cantidadProducto', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('arlEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.arl')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.cargo')),
                ('epsEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.eps')),
            ],
        ),
        migrations.CreateModel(
            name='FlujoInventario',
            fields=[
                ('idComprovante', models.AutoField(primary_key=True, serialize=False)),
                ('flujo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=1)),
                ('fechaFlujo', models.DateTimeField(auto_now_add=True)),
                ('cantidadFlujo', models.FloatField()),
                ('docEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.empleado')),
                ('flujoCorte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.corte')),
                ('insumos', models.ManyToManyField(related_name='flujos_inventario', to='Inventario.materiaprima')),
                ('materialFlu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFlujoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('flujo_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.flujoinventario')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.materiaprima')),
            ],
        ),
        migrations.AddField(
            model_name='corte',
            name='materialCorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.materiaprima'),
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('documento', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(default='Calle/Carrera 00 sur/norte #00-00', max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('celular', models.PositiveIntegerField()),
                ('fechaNac', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('ciudadPersona', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='docEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.personas'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('docCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.personas')),
            ],
        ),
        migrations.AddField(
            model_name='corte',
            name='productoCorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('docProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.personas')),
            ],
        ),
        migrations.AddField(
            model_name='flujoinventario',
            name='proveedorFlujo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.proveedor'),
        ),
        migrations.CreateModel(
            name='Satelites',
            fields=[
                ('idSatelite', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('docSatelite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.personas')),
            ],
        ),
        migrations.AddField(
            model_name='flujoinventario',
            name='flujoSatelite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.satelites'),
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('idDevolucion', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('flujo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=1)),
                ('motivo', models.CharField(default='', max_length=255)),
                ('cantidadDevo', models.FloatField(default=0.0)),
                ('fechaDevolucion', models.DateTimeField(auto_now_add=True)),
                ('devoEmpleado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventario.empleado')),
                ('devoMaterial', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.materiaprima')),
                ('devoProducto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto')),
                ('devoProveedor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.proveedor')),
                ('devoSatelite', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.satelites')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioExtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.cargo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
