# Generated by Django 5.0.1 on 2024-02-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='contraseña',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='UsuarioExtendido',
        ),
    ]
