# Generated by Django 5.0.1 on 2024-02-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_cargo_contraseña_delete_usuarioextendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corte',
            name='satelite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='Inventario.satelites'),
        ),
    ]
