# Generated by Django 5.0.1 on 2024-02-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_corte_entregado_corte_satelite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoluciones',
            name='idDevolucion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
