# Generated by Django 5.0.1 on 2024-02-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_alter_devoluciones_iddevolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujoinventario',
            name='flujoProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto'),
        ),
    ]
