# Generated by Django 5.0.1 on 2024-03-01 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_corte_fechacorte'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujoinventario',
            name='flujoCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.cliente'),
        ),
    ]
