# Generated by Django 5.0.1 on 2024-03-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_flujoinventario_flujocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujoinventario',
            name='flujo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('venta', 'Venta')], default='entrada', max_length=20),
        ),
    ]
