# Generated by Django 5.0.1 on 2024-03-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_alter_flujoinventario_flujo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arl',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eps',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
