# Generated by Django 5.0.1 on 2024-03-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0010_remove_cargo_contraseña_empleado_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujoinventario',
            name='cantidadFlujo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
