# Generated by Django 5.0.1 on 2024-03-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0011_alter_flujoinventario_cantidadflujo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoluciones',
            name='flujo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], default='entrada', max_length=20),
        ),
        migrations.AlterField(
            model_name='personas',
            name='sexo',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=20),
        ),
    ]
