# Generated by Django 5.0.1 on 2024-03-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0012_alter_devoluciones_flujo_alter_personas_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='medida',
            field=models.CharField(choices=[('m', 'metros'), ('k', 'kilos'), ('u', 'unidades')], default='m', max_length=1),
        ),
    ]
