# Generated by Django 5.0.1 on 2024-03-16 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0013_alter_materiaprima_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.cargo')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventario.empleado')),
            ],
        ),
    ]
