# Generated by Django 5.0.1 on 2024-03-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0014_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
