# Generated by Django 5.0.1 on 2024-03-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0015_delete_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleflujoinventario',
            name='cantidad_insumo',
            field=models.FloatField(default=0),
        ),
    ]
