# Generated by Django 5.0.1 on 2024-03-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0017_remove_flujoinventario_insumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujoinventario',
            name='insumos',
            field=models.ManyToManyField(related_name='flujos_inventario', to='Inventario.materiaprima'),
        ),
    ]
