# Generated by Django 5.0.1 on 2024-03-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0018_flujoinventario_insumos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='medida',
            field=models.CharField(choices=[('metros', 'Metros'), ('kilos', 'Kilos'), ('unidades', 'Unidades')], default='metros', max_length=20),
        ),
    ]
